#!/usr/bin/env bash

# Install preferred apps
function clone_from_git_ {
    # # symlink .dotfiles tmux to ~ & plugin mgr install
    ln -s $HOME/.dotfiles/tmux $HOME/.tmux
    # Tmux Plugin Manager
    echo ''
    echo "Now installing tmux plugin manager..."
    echo ''
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    
    # Speedtest-cli, pip and jq install
    echo ''
    echo "Now installing Speedtest-cli, pip, tmux and jq..."
    echo ''
    sudo apt-get install jq tmux python-pip -y
    sudo pip install --upgrade pip
    sudo pip install speedtest-cli
    
    # vimrc vundle install
    echo ''
    echo "Now installing vundle..."
    echo ''
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

    # Pathogen install
    echo ''
    echo "Now installing Pathogen..."
    echo ''
    mkdir -p ~/.vim/autoload ~/.vim/bundle && \
      curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

    # Nerdtree for vim install
    echo ''
    echo "Now installing Nerdtree for Vim..."
    echo ''
    git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree

    # Vim color scheme install
    echo ''
    echo "Now installing vim wombat color scheme..."
    echo ''
    git clone https://github.com/sheerun/vim-wombat-scheme.git ~/.vim/colors/wombat 
    mv ~/.vim/colors/wombat/colors/* ~/.vim/colors/
}
